@startuml
participant App
participant VippsBackend
participant PSP
participant PSP3DSservice

App -> VippsBackend: Approve
VippsBackend -> PSP: MakePaymentRequest pspId X
PSP -> PSP3DSservice: Prepare to host 3DS session
PSP -> VippsBackend: PSP3DSservice url
VippsBackend -> App: PSP3DSservice url
App -> App : Open url in Iframe
App -> PSP3DSservice : User completes 3DSecure
PSP3DSservice -> PSP: Share 3DS session data
App -> App : Intercepts Redirect
App -> VippsBackend: Authenticate
note right
Authenticate is the internal
Vipps terminology for a
3DS flow
end note
VippsBackend -> PSP: MakePaymentRequest pspId X
PSP -> PSP : Process Payment with 3ds session data.
PSP --> VippsBackend : Payment Result
VippsBackend --> App: Display result
@enduml
